### ISSUE TITLE
How to decrease the update interval of some sensors?

### ISSUE THREAD

**Issue by gertst** [michaelarnauts/aiocomfoconnect#16]
Some sensors, like all the temperature and humidity sensors, update their values several times per minute.

Is there a way to decrease the sensors update frequency for some sensors?

This might be a more generic question that can be solved in HA, but I can't find how to do this...

Reason: I'm passing all my ComfoConnect data to Loxone using an on-change event in HA , and the bus is sometimes flooded by update events.

Thanks!
Gert

**Comment by michaelarnauts** [comment]
I don't think this should be done in this library. But I also don't want this in the integration (the other repository). I feel that this is something that should be done in Home Assistant itself.

There are some workarounds on the HA forums by creating a template sensor IIRC.
