### ISSUE TITLE
Discover not working when old project does, can't get individual sensor

### ISSUE THREAD

**Issue by yanman** [michaelarnauts/aiocomfoconnect#4]
I'm not seeing any discovered bridges when running the new project yet the old project detects the bridge fine.

Secondly although I can get all sensors feed from 'show-sensors' the invidual ones error out :
python -m aiocomfoconnect show-sensor 276 --host 192.168.1.100
0.0
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D932F01670>

**Comment by michaelarnauts** [comment]
Can you add --debug and give me the full output?

**Comment by michaelarnauts** [comment]
Closing this one. Feel free to create a new issue if you still see this issue with the latest release.
